### ISSUE TITLE
Check for null when getting content and media

### ISSUE THREAD

**Issue by sniffdk** [prjseal/CodeShare-Umbraco-Starter-Kit-for-v8#1]
Hi Paul
Thought I'd open an issue on this 😅 
The following code is likely to cause a null reference exception at some point in time, when that image is eventually deleted without people realising it's in use:
https://github.com/prjseal/CodeShare-Umbraco-Starter-Kit-for-v8/blob/7ae2d346912de6ac24adfcf54721e023386650c1/src/CSUSK.Web/Views/Partials/Content/_MainCarousel.cshtml#L21

Do a quick null check like this:
`string imageUrl = slide.Value<IPublishedContent>("slideImage")?.GetCropUrl(1920,1080) ?? "/img/carousel.jpg";` 👍

**Comment by prjseal** [comment]
Thanks for this. I've fixed it now.
